name: webview_wrapper
description: A Flutter WebView wrapper library with enhanced features including dynamic event configuration, JavaScript communication, and external app handling.
version: 1.0.0
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/webview_wrapper

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  webview_flutter_wkwebview: ^3.22.0
  webview_flutter_android: ^4.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
