name: appsflyer_wrapper
description: A wrapper for the appsflyer_sdk to simplify integration and usage in Flutter applications.
version: 1.0.0
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/appsflyer_wrapper

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  appsflyer_sdk: ^6.12.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
