name: flutter_watermark_plus
description: A Flutter package for adding watermarks to widgets with customizable text, positioning, and styling options..
version: 1.0.0
homepage: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/flutter_watermark_plus
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/flutter_watermark_plus


environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
