name: flutter_image_tools
description: A Flutter toolkit for image processing including format conversion, cropping, and watermarking.
version: 1.0.1
homepage: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/flutter_image_tools
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/flutter_image_tools


environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
