name: app_base_kit
description: A collection of essential utilities and base classes for Flutter applications.
version: 1.0.1
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/app_base_kit

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.12
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.3.1
  event_bus_plus: ^0.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
