name: litebase
description: A lightweight SQLite database wrapper for Flutter based on sqflite, supporting both app-level and user-level databases with DAO patterns.
version: 1.0.1
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/litebase

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  sqflite: ^2.4.1
  path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0