name: app_image_picker
description: A Flutter package that provides a simplified and unified interface for picking images from gallery or camera, built on top of image_picker plugin.
version: 1.0.0
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/app_image_picker

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+24
  image_picker_platform_interface: ^2.10.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
