name: permission_wrapper
description: A Flutter permission management wrapper library based on permission_handler with enhanced features.
version: 0.0.2
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/permission_wrapper

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  permission_handler: ^12.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
