name: http_util
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  dio: 5.8.0+1
  pretty_dio_logger: 1.4.0

dev_dependencies:
  lints: 4.0.0
  test: 1.26.0
