name: lang_env
description: A Flutter utility package for retrieving device and application locale information using official Flutter APIs.
version: 1.0.0
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/lang_env

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
