name: flutter_task_queue
description: A simple and flexible task queue library, supporting both serial and parallel execution, as well as task cancellation functionality, suitable for Flutter and Dart projects.
version: 1.0.0
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/flutter_task_queue

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
