name: shared_preferences_easy
description: A simple wrapper for shared_preferences with enhanced type safety and easier usage.
version: 1.0.0
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/shared_preferences_easy

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  shared_preferences: ^2.5.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
