name: scroll_detector
description: A Flutter package for detecting scroll events and monitoring scroll state changes with customizable callbacks and thresholds.
version: 1.0.3
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/scroll_detector

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0