name: file_utils_plus
description: A comprehensive file utility library for Flutter/Dart applications.
version: 1.0.0
homepage: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/file_utils_plus
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/file_utils_plus

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  path: ^1.9.0
  mime: ^2.0.0
  crypto: ^3.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
