name: app_device_info_service
description: A Flutter package that provides comprehensive device and application information.
version: 1.0.0
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/app_device_info_service

environment:
  sdk: '>=2.19.0 <4.0.0'

publish_to: none

dependencies:
  package_info_plus: ^8.3.0
  device_info_plus:
    git:
      url: https://github.com/AlistairLi/device_info_plus.git
  flutter_udid: ^4.0.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
