name: smart_refresh_list
description: A powerful Flutter pull-to-refresh and load-more library with rich customization options and built-in state management.
version: 1.0.0
homepage: https://github.com/your_org/app_refresh
repository: https://github.com/your_org/app_refresh

environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  pull_to_refresh:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
