name: smart_refresh_list
description: This is a list refresh and pagination loading library based on "pull_to_refresh".
version: 1.0.1
repository: https://github.com/AlistairLi/my_flutter_packages/tree/main/packages/smart_refresh_list

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
